#include "smsmanager.h"
#include <QDebug>
#include <QSqlQuery>
#include <QSqlError>
#include <QUrl>
#include <QUrlQuery>
#include <QNetworkRequest>
#include <QEventLoop>
#include <QByteArray>
#include <QThread>  // AJOUT pour QThread::msleep

SMSManager::SMSManager()
{
    networkManager = new QNetworkAccessManager(this);

    // ⚠️ MODE SIMULATION (pas de clés API valides)
    apiProvider = "AC8b98a7c0d0141c5b5e4085cf13363b0d";
    apiKey = "acb2dc13c26ebba333f4db855fc5cf56";
    apiSecret = "+17755224801";
    fromNumber = "+21627981781";  // Votre numéro Tunisien

    qDebug() << "📱 SMS Manager initialisé en mode SIMULATION";

    creerTableSMS();
}

SMSManager::~SMSManager()
{
    // Le networkManager sera supprimé automatiquement
}

void SMSManager::configurerAPI(const QString &provider, const QString &key, const QString &secret, const QString &from)
{
    this->apiProvider = provider;
    this->apiKey = key;
    this->apiSecret = secret;
    this->fromNumber = from;
    qDebug() << "✅ API SMS Configurée:" << provider << from;
}

bool SMSManager::envoyerSMS(const QString &numero, const QString &message)
{
    qDebug() << "📱 Envoi SMS à" << numero << ":" << message;

    // VALIDER le numéro (format Tunisien)
    if (!numero.startsWith("+216") || numero.length() != 13) {
        qDebug() << "❌ Format de numéro invalide pour la Tunisie:" << numero;
        qDebug() << "   Format attendu: +216XXXXXXXX";
        sauvegarderSMS(-1, numero, message, false);
        return false;
    }

    // MODE SIMULATION
    qDebug() << "⚠️ MODE SIMULATION - SMS non envoyé réellement";
    qDebug() << "   Numéro:" << numero;
    qDebug() << "   Message:" << message;
    qDebug() << "   Longueur:" << message.length() << "caractères";

    // Simulation avec délai (optionnel)
    QThread::msleep(500); // 0.5 seconde de délai

    bool simulationSuccess = true; // Toujours réussi en simulation

    if (simulationSuccess) {
        qDebug() << "✅ SMS simulé envoyé avec succès!";
        qDebug() << "   (Pour envoyer réellement, configurez des clés Twilio valides)";
    }

    sauvegarderSMS(-1, numero, message, simulationSuccess);

    return simulationSuccess;
}

bool SMSManager::envoyerSMSSponsor(int idSponsor, const QString &message)
{
    QString numero = obtenirNumeroSponsor(idSponsor);
    if (numero.isEmpty()) {
        qDebug() << "❌ Numéro introuvable pour le sponsor ID" << idSponsor;
        return false;
    }

    bool resultat = envoyerSMS(numero, message);

    // Mettre à jour avec le bon ID sponsor
    if (resultat) {
        QSqlQuery query;
        query.prepare("UPDATE SMS_HISTORIQUE SET IDSPONSOR = :id WHERE ROWID = (SELECT MAX(ROWID) FROM SMS_HISTORIQUE)");
        query.bindValue(":id", idSponsor);
        query.exec();
    }

    return resultat;
}

bool SMSManager::envoyerSMSGroupe(const QList<int> &idSponsors, const QString &message)
{
    int succesCount = 0;
    for (int id : idSponsors) {
        if (envoyerSMSSponsor(id, message)) {
            succesCount++;
        }
    }
    return succesCount > 0;
}

QString SMSManager::obtenirNumeroSponsor(int idSponsor)
{
    QSqlQuery query;
    // Si votre table sponsor a une colonne TELEPHONE, utilisez-la
    // Sinon, utilisez EMAIL comme fallback
    query.prepare("SELECT TELEPHONE FROM SPONSOR WHERE IDSPONSOR = :id");
    query.bindValue(":id", idSponsor);

    if (query.exec() && query.next()) {
        return query.value(0).toString();
    }
    return "";
}

bool SMSManager::creerTableSMS()
{
    QSqlDatabase db = QSqlDatabase::database();
    bool isOracle = db.driverName().contains("ORACLE", Qt::CaseInsensitive) ||
                    db.driverName().contains("QODBC", Qt::CaseInsensitive);

    QSqlQuery query;

    if (isOracle) {
        // Vérifier si la table existe déjà dans Oracle
        QString checkTable =
            "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'SMS_HISTORIQUE'";

        if (query.exec(checkTable) && query.next()) {
            if (query.value(0).toInt() > 0) {
                qDebug() << "✅ Table SMS_HISTORIQUE existe déjà dans Oracle";
                return true;
            }
        }

        // Créer la table Oracle
        QString createTable =
            "CREATE TABLE SMS_HISTORIQUE ("
            "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "IDSPONSOR NUMBER, "
            "NUMERO VARCHAR2(20), "
            "MESSAGE VARCHAR2(4000), "
            "SUCCES NUMBER(1), "
            "HORODATAGE TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";

        if (query.exec(createTable)) {
            qDebug() << "✅ Table SMS_HISTORIQUE créée dans Oracle";
            return true;
        } else {
            qDebug() << "❌ Erreur création table SMS_HISTORIQUE Oracle:"
                     << query.lastError().text();
            return false;
        }
    } else {
        // SQLite
        QString createTable =
            "CREATE TABLE IF NOT EXISTS sms_historique ("
            "ID INTEGER PRIMARY KEY AUTOINCREMENT, "
            "IDSPONSOR INTEGER, "
            "NUMERO VARCHAR(20), "
            "MESSAGE TEXT, "
            "SUCCES INTEGER, "
            "HORODATAGE DATETIME DEFAULT CURRENT_TIMESTAMP)";

        if (query.exec(createTable)) {
            qDebug() << "✅ Table SMS_HISTORIQUE créée dans SQLite";
            return true;
        } else {
            qDebug() << "❌ Erreur création table SMS_HISTORIQUE SQLite:"
                     << query.lastError().text();
            return false;
        }
    }
}

bool SMSManager::sauvegarderSMS(int idSponsor, const QString &numero, const QString &message, bool succes)
{
    QSqlDatabase db = QSqlDatabase::database();
    bool isOracle = db.driverName().contains("ORACLE", Qt::CaseInsensitive) ||
                    db.driverName().contains("QODBC", Qt::CaseInsensitive);

    QSqlQuery query;

    if (isOracle) {
        query.prepare(
            "INSERT INTO SMS_HISTORIQUE (IDSPONSOR, NUMERO, MESSAGE, SUCCES, HORODATAGE) "
            "VALUES (:id, :num, :msg, :succ, SYSTIMESTAMP)"
            );
    } else {
        query.prepare(
            "INSERT INTO sms_historique (IDSPONSOR, NUMERO, MESSAGE, SUCCES) "
            "VALUES (:id, :num, :msg, :succ)"
            );
    }

    query.bindValue(":id", idSponsor);
    query.bindValue(":num", numero);
    query.bindValue(":msg", message);
    query.bindValue(":succ", succes ? 1 : 0);

    bool result = query.exec();

    if (result) {
        qDebug() << "💾 SMS sauvegardé dans l'historique";
        qDebug() << "   ID Sponsor:" << (idSponsor == -1 ? "Aucun" : QString::number(idSponsor));
        qDebug() << "   Succès:" << (succes ? "Oui" : "Non");
    } else {
        qDebug() << "❌ Erreur sauvegarde SMS:" << query.lastError().text();
        // Si la table n'existe pas, essayer de la créer
        creerTableSMS();
    }

    return result;
}

QList<QString> SMSManager::chargerHistoriqueSMS(int idSponsor)
{
    QList<QString> historique;
    QSqlQuery query;

    if (idSponsor == -1) {
        query.prepare("SELECT MESSAGE, HORODATAGE, SUCCES FROM SMS_HISTORIQUE ORDER BY HORODATAGE DESC");
    } else {
        query.prepare("SELECT MESSAGE, HORODATAGE, SUCCES FROM SMS_HISTORIQUE WHERE IDSPONSOR = :id ORDER BY HORODATAGE DESC");
        query.bindValue(":id", idSponsor);
    }

    if (query.exec()) {
        while (query.next()) {
            QString msg = query.value(0).toString();
            QString date = query.value(1).toDateTime().toString("dd/MM HH:mm");
            bool ok = query.value(2).toInt() == 1;
            historique.append(QString("[%1] %2 : %3").arg(date).arg(ok ? "✅" : "❌").arg(msg.left(50) + (msg.length() > 50 ? "..." : "")));
        }
    }
    return historique;
}

bool SMSManager::validerNumero(const QString &numero)
{
    // Doit être au format Tunisien: +216XXXXXXXX
    return numero.startsWith("+216") && numero.length() == 13;
}

bool SMSManager::validerMessage(const QString &message)
{
    return !message.isEmpty() && message.length() <= 160; // SMS standard: 160 caractères
}
